### ISSUE TITLE
Changing datasource

### ISSUE THREAD

**Issue by dalefrancis88** [TeamWertarbyte/material-ui-chip-input#109]
Hey,

We have a scenario where there could be around 1500 different chips. These chips have a name and description. I have two questions...

Is it possible to change the look of the autocomplete to render a more detailed react element so that i can show both title and description?

Is it possible to pass off the search function to my back-end system instead of having this do it? as in, can i tie into the autocomplete control somehow and change it's datasource?

**Comment by leMaik** [comment]
Sorry for the very late response, and I know that this might be too late. :disappointed: 

For the first part: This _might_ be possible by specifying a `<MenuItem>` node as `text` element of a value in the `dataSource`, as Material-UI will then use _that_ node instead of the text. But I'm not sure about it, and it would be pretty hacky anyway. :sweat_smile: 

The second part is pretty easy: You can pass of the search function to your back-end system by using no filter (e.g. `filter = () => true`) so that every value from `dataSource` is displayed as search result.
Then, you can populate `dataSource` with thatever your back-end serves when it searches for the string you get in the `onUpdateInput` event.

**Comment by leMaik** [comment]
Closing this after a month without response. Feel free to re-open this if you need further help.
