### ISSUE TITLE
Autocomplete not working on iOS

### ISSUE THREAD

**Issue by davidascher** [TeamWertarbyte/material-ui-chip-input#122]
It appears that the autocomplete dropdown doesn't show on small screens (iphone 5, ipod).  Is that by design? If so, can we make it customizable? I'm using material-ui-chip-input for a tagging system, and autocomplete is a pretty critical requirement.

**Comment by leMaik** [comment]
This is of course not by design. Unfortunately, I can't reproduce this bug; the autocomplete menu works fine on my Nexus 4 and I don't have an iPhone to test things on.
Are there any errors on the console when using the component on an iPhone 5 or iPod? Do you find the element in the element tree and could you tell me where it is located?

**Comment by davidascher** [comment]
this is a problem upstream i believe with material-ui.  will close this issue.

**Comment by leMaik** [comment]
Would you mind linking to the upstream issue? That might help other people that have the same problem.

**Comment by davidascher** [comment]
Sure thing: https://github.com/callemall/material-ui/issues/3638 is my best guess.

**Comment by leMaik** [comment]
I'll keep this issue open to keep an eye on it. :+1:

**Comment by aayush2252** [comment]
I also found that issue in my iphone 7, 6S and 5S. I guess it's versioning issue because it works fine with 10.2.X version but not with 10.3.X.

**Comment by leMaik** [comment]
The upstream issue seems to be fixed. :+1:
