### ISSUE TITLE
Non character keypress clear input value

### ISSUE THREAD

**Issue by rullyramanda** [TeamWertarbyte/material-ui-chip-input#126]
If i press backspace (keycode: 8) it removes the entire text that was typed, which is not what i want, as i want to delete one char only. At first i think this only occurred when i press backspace, but it turns out it affects some keys too like shift, ctrl, command, capslock etc. except enter.

**Comment by leMaik** [comment]
Looks like a regression introduced by #124 :confused: I'm trying to fix it and will release a patch soon.

**Comment by leMaik** [comment]
@foloinfo Would you mind checking if my fix broke your fix for #124? :smile:

**Comment by foloinfo** [comment]
@leMaik Hi! I checked this patch and unfortunately it broke fix for #124 .

I found that I misunderstood behaviour of `handleKeyUp`, I thought it `clears input if user hits Enter` but it was to `set inputValue if user hits anything other than Enter`.
In order to handle IME, I need to `ignore Enter key if keypress event is NOT fired`(means `clear the input when Enter key was pressed AFTER keypress is fired.`).
ref: [javascript - Is it OK to ignore keydown events with keyCode = 229? - Stack Overflow](https://stackoverflow.com/questions/25043934/is-it-ok-to-ignore-keydown-events-with-keycode-229)

I feel it's really bothersome... anyway I managed to fix this bug without causing #126 so I made pull-request #127 . Please let me know if this would cause something else!
