### ISSUE TITLE
Support japanese

### ISSUE THREAD

**Issue by hurano** [TeamWertarbyte/material-ui-chip-input#160]
I tried to type Japanese but it doesn't work. Could you support multiple languages?

**Comment by leMaik** [comment]
This was already fixed a bunch of times: #144 #124 #126

Could you please explain what exactly doesn't work and how the component behaves and should behave? "Does not work" is not a good starting point for debugging. :sweat_smile: 

@foloinfo I think I broke this again. :cry: Is there any way this could be tested (and automatic way would be even better).

**Comment by hurano** [comment]
If its Chinese character, it works. but if i try hiragana, it disappear after I type enter key. 
https://www.screencast.com/t/wjopnX8fcR

**Comment by leMaik** [comment]
@hurano PR welcome. I can't reproduce these bugs unfortunately.

**Comment by foloinfo** [comment]
@leMaik I've never written a test involve key press behaviour, but basically what matter is the `keyCode` and `state of keypress`, so if you call `handleKeyDown`, `handleKeyUp`, and `handleKeyPress` in the same manner as how IME behaves then you can test this with something like jest, I guess.

@hurano Have you tried with material-ui 0.18? [Some versions of material-ui have bug with this library](https://github.com/TeamWertarbyte/material-ui-chip-input/issues/144#issuecomment-329139219).

**Comment by leMaik** [comment]
@foloinfo Hm… mocking IME with jest sounds like a bad idea now that I think about it. It should be tested in browsers.
Downgrading material-ui sounds like a bad solution, since this library only (officially) supports material-ui@0.19.x. I'd really prefer to get this bug fixed. :)

**Comment by foloinfo** [comment]
@leMaik I though of something like these.
[dmauro/Keypress](https://github.com/dmauro/Keypress/blob/development/test/tests.coffee)
[RobertWHurst/KeyboardJS](https://github.com/RobertWHurst/KeyboardJS/blob/master/test/keyboard.spec.js)
However I’m not sure it’s a good idea or not. Seems to me there are not much other way.

Automated test in browsers... I’ve only used phantomjs, so I looked at API and Documentation, but seems like they don’t have any mechanism involves IME. It is possible to insert Japanese values into forms, but I’m not sure it actually type these chars (probably not).

I mainly use Rails and React, and most of my tests are written in E2E like capybara + phantomjs, so that’s all I know at this point. If there are other testing solutions, I would like to know!

**Comment by hurano** [comment]
Did you guys modify the demo? I tried today. and it is working perfectly for Japanese. Thanks.

**Comment by leMaik** [comment]
@hurano I updated the demo, but that shouldn't have changed anything… … … should. Maybe the demo was just old, I'm sorry!

**Comment by leMaik** [comment]
@hurano Also, the demo now uses React 16, which may or may not affect the japanese input problems.

**Comment by hurano** [comment]
Thank you so much for your quick support. I love your work. Thanks.
