### ISSUE TITLE
obfuscated version takes wrong value

### ISSUE THREAD

**Issue by amitos80** [TeamWertarbyte/material-ui-chip-input#175]
i'm working with https://github.com/marmelab/admin-on-rest which uses ChipInput, recently i noticed wrong values are taken after selection. when researching further @TarSzator noticed the problem was with obfuscated version of ChipInput. i can confirm after replacing to the original file it did fix the issue. can someone please take a look?

**Comment by leMaik** [comment]
We don't provide any "obfuscated" version of ChipInput, so please use the original files, that should fix it.

**Comment by TarSzator** [comment]
Can this ticket please be reopened?

The situation is that the version delivered via NPM is NOT working croorectly. It can't be a solution to copy the file from GitHub into our projects!

Obfuscated might be the wrong word but it is babel-ified" in a lib folder when we install it via NPM. This js file does NOT work correctly.

**Comment by leMaik** [comment]
@TarSzator Neither me nor other users of this library seem to have this issue. :open_mouth: Are you sure you don't have some bad webpack configuration and are trying to transpile `node_modules` or something? Please give me some more information, so that I can look into this. Some error or stack trace might help here. :wink: 

PS: You got it! :tada: We aim to make the name perfectly match our work. :wink:

**Comment by TarSzator** [comment]
Will check this later today.

That sure could be the explanation for why we are the only once having this problem so fare.

I will write here when I have more information.

**Comment by TarSzator** [comment]
I used react-scripts to build and it seems by default they babelify node_modules. After I ejected the project from react-scripts and changed the config to exclude node_modules it worked.

IMHO ticket can be closed.

**Comment by leMaik** [comment]
@TarSzator Glad you found the issue, this might help other people, too!
