### ISSUE TITLE
Reset empty input's height

### ISSUE THREAD

**Issue by Sharlaan** [TeamWertarbyte/material-ui-chip-input#19]
An image is better than words:
![resetemptyinputheight](https://cloud.githubusercontent.com/assets/2692027/18990251/ea12dc9c-8710-11e6-979a-2d2278f2a9f0.png)

Looks like the input is taking unnecessary and ugly space ?

While at it, i noticed also when typing some search text, then exiting without selecting any option, the input still conserve the typed text instead of reseting onBlur ?

**Comment by leMaik** [comment]
This is by design. You may think that this space is "ugly", but the user needs some space to click and edit stuff, so that's what this is for. Angular Material also does this, and I didn't have a better idea. It's kind of related to #16 which I closed for that reason.

Resetting the search text on blur is a good idea. I'll add that.

**Comment by Sharlaan** [comment]
Suggestion: how about "deporting" this input inline at end of the Chips container ?

**Comment by leMaik** [comment]
The problem is that you won't see the typed text if the input is too small and located at the very right of the container. I'd like to keep it as it is.

**Comment by leMaik** [comment]
...or maybe I could expost an `inputStyle` prop so that you can customize it yourself? :wink:
