### ISSUE TITLE
Margin "normal" mixed behavoiur

### ISSUE THREAD

**Issue by hill84** [TeamWertarbyte/material-ui-chip-input#217]
When I set the property `margin` to `normal` the requested margin is correctly set (margin-top: 16px, margin-bottom: 8px) but I receive the following error in console: 

> Invalid prop `margin` of value `normal` supplied to `Input`

It seams that the only two valid options are `dense` or `none`, but to be consistent with Material-UI v.1.x.x it should also support `normal`.

Also, the margin property is not mentioned in the README.md file.

**Comment by jannnik** [comment]
I also wondered why it is not consistent with Material-UI 1.x.x. Did you get margin: dense working? I I use `margin: dense` the blinking indicator of the textfield is not vertically centered with the chips.

**Comment by leMaik** [comment]
According to Material-UI, only `dense` and `none` are supported values for Input. https://material-ui.com/api/input/ That's why you get the error, since we just pass that property through.

That said, the TextField does support `normal` and I'll make the ChipInput support the TextField's margin values.

**Comment by leMaik** [comment]
Can't reproduce this anymore. Maybe it was a Material-UI bug. :thinking:
