### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by bonbonio** [TeamWertarbyte/material-ui-chip-input#270]
Hi,

I see no changelog for the next release or timeline; I want to use this with Material-UI  3.9.x as an email input field, but I am concerned this project seems a little abandoned.

What is the timeline for the 1.0.0 and what is part of that intended release.

**Comment by leMaik** [comment]
The last release [was 15 days ago](https://github.com/TeamWertarbyte/material-ui-chip-input/releases/tag/v1.0.0-beta.15) this project is not abandoned at all! We are maintaining it since 2016 and have no plans to stop doing so. 

For MUI 3.9.x, use the @next tag on npm.

**Comment by bonbonio** [comment]
That is a beta release - there are no notes to give any detail. The version on npm without the @next is still 0.0.19 - I mean no offence but its a great component - I just need to know when the beta and the product will become a 1.0.0 and have a changelog

Thanks Maik

**Comment by leMaik** [comment]
> there are no notes to give any detail

There are changelogs available on [the releases page](https://github.com/TeamWertarbyte/material-ui-chip-input/releases)

> I just need to know when the beta and the product will become a 1.0.0 and have a changelog

For the changelog, see the link above. We don't have a roadmap because we provide these components for free and thus have no obligations regarding time and set of features. That said, the beta is pretty stable (actually, it's the only component we didn't publish as non-beta yet). Do you need 1.0.0 for peace of mind or is there an actual feature that you need or a bug that you'd like to see fixed?

> I mean no offence but

Communication pro tip: Comments don't come across the internet less offensive by writing "no offense but".
