### ISSUE TITLE
How to programmatically add chips to component

### ISSUE THREAD

**Issue by sniggitysnax** [TeamWertarbyte/material-ui-chip-input#282]
More of a question, although I haven't found it in any forums, etc. 

Is it possible to programmatically add chips to the component?

EX: Based on a user selection in my app, I want to populate a chip input component with 10 specific chip values programmatically. This could be before or after the user has already input some of their own custom chip values.

I've tried updating the state that drives the value prop, but chips don't visually show.

I've tried passing the entire payload of chip values through the onRequestAdd method, but again they do not show visually.

Is there any way to accomplish this?

**Comment by leMaik** [comment]
You'll have to use the controlled mode, that way you can add/remove chips by changing the `value` prop from your component.

An example on how to use controlled mode is available here: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/stories/examples/ControlledChipInput.js

> I've tried updating the state that drives the value prop, but chips don't visually show.

Weird… Please show us a Code Sandbox that reproduces the problem so that we can help you.
