### ISSUE TITLE
onChange returns only the values not the native element

### ISSUE THREAD

**Issue by cbelhaoues** [TeamWertarbyte/material-ui-chip-input#294]
The onChange function returns only the values of the chips in an array format and not the native element, so it's impossible to control the behavior based on the event.target information.

I think it's better to keep the native element untouched since the chip-input is an html node, that way the users have the full flexibility and compatibility with any other html element.

**Comment by leMaik** [comment]
What do you mean by "native element"? `onChange` indeed returns the values of the chips, that's what it's supposed to do. If you want to customize the chips, you can use the chipRenderer prop.

**Comment by cbelhaoues** [comment]
I mean by "native element" an HTML node with all its props and data (for ex: event.target is defined and contains all the information). We are used to have from the onChange is the ability to read the props of the node (like event.target.name, event.target.id...) and I was surprised that the onChange sends only the value of the chips which is a bit messy because we expect from a change event to give us full information of the node that triggered the change and not only the value(s) that the node holds or generates (the values are accessible through event.target.value).

**Comment by leMaik** [comment]
Since the chip input isn't a native element, there is no "e" or "e.target" that we could provide to you. The only native thing that causes the event would be the input if the user adds a chip, or the button if the user deletes a chip. This component abstracts from those things and provides a high level view: you put an array of values in, you get an array of values out.

I don't see how this is "a bit messy". If you need to know where the event came from, you can still add that info in the callback function.

By the way, "I think it's better" and "I was surprised" don't really convince me. :sweat_smile: Please provide some code and show me what you'd like to do and then I can show you how to do it without any changes to the chip-input.

**Comment by cbelhaoues** [comment]
Thanks for the explanation :-)
All I want is just to have the full information that "e.target" gives from onChange or equivalent function like all the components of Material UI (as the code uses MUI components behind the scene).

**Comment by cbelhaoues** [comment]
To give more precision, I'm talking about this function (handleUpdateInput) that alters the event to return only its value. C.f https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L375
I was expecting that the full event returned not just its value.
In all cases I found a work around to make it work in my code. Thanks for your help.

**Comment by leMaik** [comment]
@cbelhaoues But `onUpdateInput` is actually called with the full event: https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L381
