### ISSUE TITLE
Feature request ErrorStyle

### ISSUE THREAD

**Issue by voxbox-io** [TeamWertarbyte/material-ui-chip-input#33]
Hi!

I think that just by adding:

```
    color: props.errorStyle ? props.errorStyle.color : errorColor
```

instead of:

```
    color: errorColor
```

in the error style, you could make it customizable.

Just a thought!

**Comment by leMaik** [comment]
Sounds good to me! Want to submit a PR (please also add it to the readme)? :+1:

**Comment by voxbox-io** [comment]
Ok will do so by EOW!

**Comment by leMaik** [comment]
@voxbox-io I think I was wrong about the handling of `errorColor`. The style should be `{ ...props.errorStyle, color: <check if error> ? (props.errorStyle.color || errorColor) : errorcolor }`, so that it shows the user-specified color if there is an error and falls back to the default color otherwise.

**Comment by leMaik** [comment]
@voxbox-io `errorStyle` currently works the same as for Material UI's `TextField`. I wouldn't like to add it then, seems somewhat non-straightforward. :confused:
