### ISSUE TITLE
Uncaught TypeError: chip.trim is not a function

### ISSUE THREAD

**Issue by Shaxmatist** [TeamWertarbyte/material-ui-chip-input#81]
Error **Uncaught TypeError: chip.trim is not a function** if dataSource like from [example](http://www.material-ui.com/#/components/auto-complete):
```javascipt
const dataSource1 = [
  {
    text: 'text-value1',
    value: (
      <MenuItem
        primaryText="text-value1"
        secondaryText="&#9786;"
      />
    ),
  },
  {
    text: 'text-value2',
    value: (
      <MenuItem
        primaryText="text-value2"
        secondaryText="&#9786;"
      />
    ),
  },
];
```

**Comment by leMaik** [comment]
The chip value is not meant to be an element. :open_mouth: It should be a string or an object, as shown in the examples.

**Comment by Shaxmatist** [comment]
Thanks. I was looking for a way to customize popover(menu) items. Maybe you can suggest it? And way to keep focus on first item, when input updates.

**Comment by leMaik** [comment]
Sorry for the late response, @Shaxmatist, it's been a pretty busy week.

At the moment, there is no way of customizing the popover menu items, but you could probably add `popoverMenuStyle` and `popoverMenuItemStyle` props that allow customizing this. Feel free to submit a PR that does this. :+1: 
Keeping the focus on the first item: It's not supported and I don't really see why this should be supported.

**Comment by leMaik** [comment]
@Shaxmatist Closing this after two weeks without any response. Feel free to re-open this if you have further questions. :+1:

**Comment by techniq** [comment]
I ran into this error today while trying to port from `<AutoComplete />` to `<ChipInput />` and found it was due to AutoComplete defaulting [dataSourceConfig](http://www.material-ui.com/#/components/auto-complete) to `{ text: 'text', value: 'value' }` but ChipInput expects the dataSource to be an array of strings by default?

Maybe worth adding an additional check [here](https://github.com/TeamWertarbyte/material-ui-chip-input/blob/master/src/ChipInput.js#L321) if chip is an object to parse is using the same default dataSourceConfig?

**Comment by leMaik** [comment]
@techniq I'd prefer not to introduce the breaking change of adding a default value for `dataSourceConfig` to `ChipInput`. The readme already makes it pretty clear how `dataSourceConfig` works:

> If [`dataSourceConfig` is] not specified, the dataSource must be a flat array of strings.

**Comment by techniq** [comment]
I overlooked the dataSourceConfig initially and somewhat expected it to be the same knowing it was using AutoComplete under the hood.  Not a big deal, but the error I ran into (`chip.trim is not a function`) I at first attributed it to me using Material-UI 0.17 and thought there was a compat. problem without looking at the docs closely.  I later realized when I looked at the underlying storybook code for the `objects as chips` examples.

I don't think it would be a breaking change since the value of `chip` could be checked if it's a string or object and handled accordingly, so it wouldn't break any existing code using an array of strings.

Once again, not a big deal, just a suggestion.  Thanks for the quick response.

**Comment by leMaik** [comment]
I'll keep it as it is then, for now. Material-UI 1.x doesn't have a `AutoComplete` component yet, so maybe we'll have to re-write it anyway and then it will ultimately be an implementation detail.

I don't want to add any code just to make the component work if its configuration is wrong.
